# Generated by Django 3.1.3 on 2022-07-11 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestsession',
            name='req_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodrequestsession',
            name='till_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodrequeststatus',
            name='donation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
