# Generated by Django 3.1.3 on 2022-07-13 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220711_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='last_donated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
