# Generated by Django 3.1.3 on 2022-07-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220713_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='blood_group',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
