# Generated by Django 3.1.3 on 2022-07-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220715_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='blood_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.bloodgroup'),
        ),
    ]
